--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/ruby:2.6.3-stretch-node"
    executor: ruby/default
    steps: 
      - checkout
      - 
        run: "gem install bundler"
      - 
        run: 
          command: "bundle -v"
          name: "Which bundler?"
      - 
        run: "bundle check || bundle install"
      - 
        run: "bundle exec rake test"
      - 
        store_test_results: test/reports
      - ruby/bundle-install
orbs: 
  ruby: circleci/ruby@0.1.2
version: 2.1
